### ISSUE TITLE
Return scale dependent statistics as masked array

### ISSUE THREAD

**Issue by pastewka** [ContactEngineering/SurfaceTopography#225]
Right now we are returning a list with `None` value for length-scales that have no data points. A numpy masked array should actually be suitable for this (and be more performant).

This would be a major API change.

@sannant - Any thoughts on this?

**Comment by sannant** [comment]
masked arrays sometimes have weird inconsistent unexpected behaviour. we had issues in the interaction potentials because of that. I think this is the reason why we avoid them here as well. we should write this properly down so we do not get temoted every new year. Sent from Android deviceOn 7 Oct 2022 22:53, Lars Pastewka ***@***.***> wrote:
Right no we are returning a list with None value for length-scales that have no data points. A numpy masked array should actually be suitable for this (and be more performant).
This would be a major API change.
@sannant - Any thoughts on this?

**Comment by pastewka** [comment]
The problem is conversion of masked arrays to normal ones. (The fill value may change.) If it is clear that the function returns a masked array, there should be no ambiguity.

**Comment by pastewka** [comment]
This has been implemented in V1.1
